version: '3.7'

services:
  nginx:
    build:
      context: ./
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    working_dir: /app
    
